import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {useEffect} from "react";

export default function Home() {

  const path = '/notes/';
  const ext = '.mp3';

  const whiteKeys = [
    'C3',
    'D3',
    'E3',
    'F3',
    'G3',
    'A3',
    'B3',
    'C4',
    'D4',
    'E4',
    'F4',
    'G4',
    'A4',
    'B4',
    'C5',
  ];

  const keyboard = {
    'KeyW': 'C-3',
    'KeyA': 'C3',
    'KeyS': 'D3',
  }

  const playNote = (keyId) =>{
    document.getElementById(keyId).play();
  }

  const keyDownHandler = (e) => {
    let id = keyboard[e.code];
    playNote(id);
  }

  useEffect(() => {
    document.addEventListener("keydown", keyDownHandler);
    // clean up
    return () => {
      document.removeEventListener("keydown", keyDownHandler);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>keyboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          keyboard
        </h1>

        <p className={styles.description}>
          Care to play a little tune?
        </p>

        <div className={styles.piano}>

          {whiteKeys.map((key) => {
            return(
              <div className={styles.whiteKey} key={key}>
                <audio id={key} src={`${path}${key.toLowerCase()}${ext}`}/>
                {!(key.includes('E') ||
                   key.includes('B') ||
                   key.includes('5'))
                &&
                <div className={styles.blackKey}>
                    <audio id={`${key[0]}-${key[1]}`} src={`${path}${key[0].toLowerCase()}-${key[1]}${ext}`}/>
                </div>
                }
                <p className={styles.whiteNote}>{key}</p>
              </div>
            )
          })
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}