import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {useEffect} from "react";

export default function Home() {

  const whiteKeys = [
    'C3',
    'D3',
    'E3',
    'F3',
    'G3',
    'A3',
    'B3',
    'C4',
    'D4',
    'E4',
    'F4',
    'G4',
    'A4',
    'B4',
    'C5',
  ];
  const blackKeys = [
    '',
  ];

  const keyDownHandler = (e) => {
    switch (e.value) {
      case'A':

        break;
      default:
    }
    console.log(`You pressed ${e.code}.`);
  }

  useEffect(() => {
    document.addEventListener("keydown", keyDownHandler);
    // clean up
    return () => {
      document.removeEventListener("keydown", keyDownHandler);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>keyboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          keyboard
        </h1>

        <p className={styles.description}>
          Care to play a little tune?
        </p>

        <div className={styles.grid}>
          {[...Array(15)].map((note, i) => {
            return(
              <div key={i} className={styles.whiteKey}>
                {!((whiteKeys[i].includes('E')) ||
                   (whiteKeys[i].includes('B')) ||
                   (whiteKeys[i].includes('5'))) && <div className={styles.blackKey}/>}
                <p className={styles.whiteNote}>{whiteKeys[i]}</p>
              </div>
            )
          })
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
